services:

  rabbitmq-hotel-quarto:
    image: rabbitmq:3-management

    container_name: rabbitmq-hotel-quarto

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: always

  hotel-quarto:

    build: .

    container_name: hotel-quarto

    ports:
      - "9533:9533"

    restart: always

    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      RABBITMQ_URL: ${RABBITMQ_URL}

    depends_on:
      - rabbitmq-hotel-quarto

    command: >
      sh -c "
      npx prisma db push &&
      npm run dev
      "